pipeline:
  name: Build python-ci-harness-test
  identifier: Build_zacharyzjamison_python_ci_harness_test_1726427618504
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Python Test
                  identifier: Run_Python_Test
                  spec:
                    shell: Sh
                    command: python test.py -v
                  description: Will run the python Test
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: zacharyzjamison/python-ci-harness-test
        build: <+input>
